### PR TITLE
Migrate DevelopmentProcess

### PR DESCRIPTION
**Pull request by ThomasArdal**
This PR still needs a lot of work. This is a direct port of the old wiki page. This PR is intended as a container for the progress on this issue as well as to host a place to discuss which changes to make.

### CODE REVIEW

**Comment by ThomasArdal** [comment]
@atifaziz I know about the highlighting. Do we have a favorite language setting for highlighting command line?

**Comment by atifaziz** [comment]
You can use `bash`.

**Comment by ThomasArdal** [comment]
This PR is ready for a review.

**Comment by atifaziz** [comment]
@ThomasArdal Have you tested the page locally? It's not working on my end at all. Jekyll refuses to process the file and I think it's because your lines end in CR alone and not LF. It's not possible to review the changes either as Git & GitHub diffs are appearing off. Part of this is my fault as I don't have a `.gitattribtues` file in the repo yet. However, local testing should have revealed this issue before committing the changes. I think it would be best to revert 281a3a6..9761e6d and start over. Also, when you do that, please make the commit atomic. If you find yourself using *and* in the commit message then it's usually a sign that it should have been two commits in the first place. It makes review easier and quicker and also helps to back-out one change without collaterally losing logically unrelated changes (because they happen to be in the same commit).

**Comment by ThomasArdal** [comment]
@atifaziz I agree with everything you say. I'm on the road why I haven't tested the page. I will do that later today when I return to my developer machine.

I would suggest to make this into a single commit. The reason for it to be split up was more for me to split the task up in chunks and not because every commit makes sense on their own. Having a version were there's references to the source repo at google doesn't makes sense at all.

Regarding the "and" I usually never do that. But my "git add -p" didn't work because of the missing .gitattributes file.

Would be ok if I create a new PR including a single commit with the current version (after I test it with Jekyll)?

**Comment by atifaziz** [comment]
@ThomasArdal I'm fine if you want to do redo this as one commit now that you know what shape it will have in the end.

I don't think you need to open a new PR. History is history and it's published. I would revert the changes from the commits so far in a single commit. This will put back the repo in the state it was before 281a3a6 (your initial port).

If you'd rather not pollute the history then the other option is to delete your repo & re-folk, though it will leave dangling commits. You'll probably want a new PR in this case.

**Pull request closed without merging**
