### PR TITLE
Add Sql server compact wiki

### PR DESCRIPTION
**Pull request by fiftynineseconds**

### CODE REVIEW

**Comment by atifaziz** [comment]
Would be great to get input from @erikej as well.

**Comment by ErikEJ** [comment]
@atifaziz I will have a look, seems there are some broken links.

**Comment by ErikEJ** [comment]
@fiftynineseconds Using the download link LGTM

**Comment by atifaziz** [comment]
@fiftynineseconds We're almost there! It would help with testing and integrity to merge with upstream/master. I noticed [you already did that](https://github.com/fiftynineseconds/www/commit/82afbc6e54f7ab2757ace04666f7c2d6ee7bc644) but in [your master branch](https://github.com/fiftynineseconds/www/commits/master) whereas I was expecting to find it in your [SqlServerCompact](https://github.com/fiftynineseconds/www/commits/SqlServerCompact) branch. Once I've merged your PR, though, that'll give your repo an extra/orphaned head. To clean-up, you'll have to re-fork.

**Comment by fiftynineseconds** [comment]
Right, sorry. I merged your upstream/master with my master then merged that with my branch but forgot to push the changes. How does it look now? Next time I'll merge your upstream/master into my working branch before creating a PR.

Also, the page has a couple references to the sample web.config that point to Google code. What do you think about adding a variable to _config.yml like:

`samplewebconfig: http://elmah.googlecode.com/svn/tags/REL-1.2-SP1/samples/web.config`

so that it doesn't have to be updated later when Google code shuts down, for example:

 `If you look in the [sample web.config]({{ site.samplewebconfig }}) file`

**Comment by atifaziz** [comment]
@fiftynineseconds Looks all good now!

As for the sample `web.config` references, the problem is a lot bigger as links to resources on [the project site on Google Code](https://elmah.googlecode.com) are many and spread throughout the wikis (not to mention the code, packages and the web). Introducing a variable in the site config for each and every case would pollute the variable space and the markdown. The real doomsday deadline for [the Google Code shutdown](http://google-opensource.blogspot.co.uk/2015/03/farewell-to-google-code.html) is really Jan 2016 when all links will go dead. Until then, there's a bit of time to do a single sweeping review of all links (most of which I'm hoping could be done with a grep of sorts). Meanwhile, the goal is to find a home for all project assets (docs, sources, issues, etc.) so one can link to them again.

Perhaps rather than have a variable per link, one can imagine variables for some roots (like `svnrepo: http://elmah.googlecode.com/svn/`) but that assumes the links are themselves portable in format among hosts and I don't think that's the case. It might just be too early to generalize on this at the moment.

That all said, the [old Subversion repo](http://elmah.googlecode.com/svn/) has already been [migrated to Assembla](https://www.assembla.com/code/elmah/subversion/nodes) so you can fix that sample `web.config` link to point [to](https://www.assembla.com/code/elmah/subversion/nodes/926/tags/REL-1.2-SP1/samples/web.config):

    https://www.assembla.com/code/elmah/subversion/nodes/926/tags/REL-1.2-SP1/samples/web.config

**Comment by atifaziz** [comment]
[Published](https://elmah.github.io/a/sql-server-compact/)!

**Pull request merged**
